steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/sample-app:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sample-app:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '--region', 'europe-west1', '--image', 'gcr.io/$PROJECT_ID/sample-app', '--platform', 'managed', 'sample-website-$BRANCH_NAME' ]
images:
  - 'gcr.io/$PROJECT_ID/sample-app'
